- name: Datanode Configuration
  
  hosts: Datanode
  
  vars:
    - jdk_dir: /root
    - hadoop_dir: /root
    - hdfs_dir: /slavenode
    - node: data
    - ip_addr: 192.168.29.47
    - port: 9009
  
  tasks:
    - name: Copying JDK
      copy:
        src: "{{ jdk_dir }}/jdk-8u171-linux-x64.rpm"
        dest: /root/
      register: x

    - name: Copying Hadoop
      copy:
        src: "{{ hadoop_dir }}/hadoop-1.2.1-1.x86_64.rpm"
        dest: /root/
      register: y

    - name: Installing JDK
      command: "rpm -i {{ jdk_dir}}/jdk-8u171-linux-x64.rpm"
      when: x.failed == false
      register: p

    - name: Installing Hadoop
      command: "rpm -i {{ hadoop_dir }}/hadoop-1.2.1-1.x86_64.rpm --force"
      when: y.failed == false
      register: q
      when: p.failed == false

    - name: Creating Datanode directory
      file:
        path: "{{ hdfs_dir }}"
        state: directory

    - name: Configuring hdfs-site
      template:
        src: "hdfs-site.xml"
        dest: "/etc/hadoop/hdfs-site.xml"
      when: q.failed == false
      register: a

    - name: Configuring core-site 
      template:
        src: "core-site.xml"
        dest: "/etc/hadoop/core-site.xml"
      when: q.failed == false
      register: b

    - service:
        name: "firewalld"
        state: stopped

    - name: Starting the Datanode Server
      command: "hadoop-daemon.sh start datanode"
      register: z
      when: a.failed == false and b.failed == false

    - debug: 
        var: z

    - name: Checking the Connection
      command: "jps"
      when: z.failed == false
      register: k

    - debug:
        var: k
